image: daocloud.io/baidao/node-docker:7

stages:
  - test
  - build

before_script:
  - docker login -u $DAOCLOUD_USERNAME -p $DAOCLOUD_PASSWORD daocloud.io

test:
  stage: test
  tags:
    - node-docker-gmg
  script: echo 'test'
   
build: 
  stage: build
  only:
    - develop
    - master
  tags:
    - node-docker-gmg
  script:
    - bash push-daocloud.sh 



