image: daocloud.io/baidao/node-docker:7
stages:
  - test
  - build

test:
  stage: test
  tags:
    - gmg-adviser-qrload-service
  script:
   
before_script:
  - docker login -u $DAOCLOUD_USERNAME -p $DAOCLOUD_PASSWORD daocloud.io

build: 
  stage: build
  only:
    - develop
    - master
  tags:
    - gmg-adviser-qrload-service
  script:
    - bash push-daocloud.sh 



