image: daocloud.io/baidao/node-docker:7

stages:
  - test
  - build

before_script:
  - echo 1234567
  - docker login -u $DAOCLOUD_USERNAME -p $DAOCLOUD_PASSWORD daocloud.io

test:
  stage: test
  tags:
    - gmg-adviser-qrload-service
  script: echo 'test'
   
build: 
  stage: build
  only:
    - develop
    - master
  tags:
    - gmg-adviser-qrload-service
  script:
    - bash push-daocloud.sh 



